# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'botmanagerui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1089, 840)
        MainWindow.setMinimumSize(QtCore.QSize(966, 600))
        MainWindow.setAcceptDrops(True)
        MainWindow.setStyleSheet("/* General Styles */\n"
"QWidget {\n"
"    color: #FFFFFF;\n"
"    background-color: #2C2C2C;\n"
"    font-family: \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* QPushButton Styles */\n"
"QPushButton {\n"
"    background-color: #4CAF50;\n"
"    border: none;\n"
"    color: #FFFFFF;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-size: 14px;\n"
"    margin: 4px 2px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;\n"
"}\n"
"\n"
"/* QLineEdit Styles */\n"
"QLineEdit {\n"
"    background-color: #3C3C3C;\n"
"    border: none;\n"
"    color: #FFFFFF;\n"
"    padding: 8px 12px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #4CAF50;\n"
"}\n"
"\n"
"/* QComboBox Styles */\n"
"QComboBox {\n"
"    background-color: #3C3C3C;\n"
"    border: none;\n"
"    color: #FFFFFF;\n"
"    padding: 8px 12px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #454545;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #3C3C3C;\n"
"    color: #FFFFFF;\n"
"    selection-background-color: #4CAF50;\n"
"}\n"
"\n"
"/* QCheckBox Styles */\n"
"QCheckBox {\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    background-color: #3C3C3C;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #4CAF50;\n"
"}\n"
"\n"
"/* QProgressBar Styles */\n"
"QProgressBar {\n"
"    background-color: #3C3C3C;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #4CAF50;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"   background-color: #3C3C3C;\n"
"}\n"
"\n"
"QMenu {\n"
"                background-color: #2C2C2C;\n"
"                color:  #FFFFFF;\n"
"                font-size: 14px;\n"
"            }\n"
"            QMenu:hover{\n"
"                background-color: #4CAF50;\n"
"            }\n"
"            QMenu::item {\n"
"                padding: 6px 16px;\n"
"            }\n"
"            QMenu::item:selected {\n"
"                background-color: #4CAF50;\n"
"            }\n"
"            QMenu::item:hover {\n"
"                background-color: #4CAF50;\n"
"            }\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAcceptDrops(True)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setStyleSheet(" color: #ffffff;\n"
"    border: 1px solid #444;\n"
"    border-radius: 5px;")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.listpreview = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listpreview.sizePolicy().hasHeightForWidth())
        self.listpreview.setSizePolicy(sizePolicy)
        self.listpreview.setAcceptDrops(True)
        self.listpreview.setObjectName("listpreview")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.listpreview)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_2)
        self.listfileid = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listfileid.sizePolicy().hasHeightForWidth())
        self.listfileid.setSizePolicy(sizePolicy)
        self.listfileid.setAcceptDrops(True)
        self.listfileid.setObjectName("listfileid")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.listfileid)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_7.addWidget(self.lineEdit_2)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setAcceptDrops(False)
        self.textEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_8.addWidget(self.lineEdit_4)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_8.addWidget(self.lineEdit_3)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget.setMinimumSize(QtCore.QSize(605, 300))
        self.tableWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tableWidget.setStyleSheet("/* QTableWidget Styles */\n"
"QTableWidget {\n"
"    background-color: #2C2C2C;\n"
"    color: #FFFFFF;\n"
"    gridline-color: #3C3C3C;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background-color: #2C2C2C;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #3C3C3C;\n"
"    color: #FFFFFF;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QTableWidget::corner-widget {\n"
"    background-color: #3C3C3C;\n"
"}\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(66, 66, 66);\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.frame_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_3, 1, 1, 2, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_10.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_10.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_10.addWidget(self.pushButton_11)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_4, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1089, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu = QtWidgets.QMenu(self.menuFile)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_5)
        self.menuFile.addAction(self.menu.menuAction())
        self.menuFile.addAction(self.action_3)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_7)
        self.menu_2.addAction(self.action_8)
        self.menu_3.addAction(self.action_9)
        self.menu_3.addAction(self.action_10)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(self.listfileid.clear) # type: ignore
        self.pushButton_2.clicked.connect(self.listpreview.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.pushButton_9)
        MainWindow.setTabOrder(self.pushButton_9, self.pushButton_10)
        MainWindow.setTabOrder(self.pushButton_10, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.listpreview)
        MainWindow.setTabOrder(self.listpreview, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.pushButton_8)
        MainWindow.setTabOrder(self.pushButton_8, self.listfileid)
        MainWindow.setTabOrder(self.listfileid, self.pushButton_3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "مدیریت بات"))
        self.groupBox.setTitle(_translate("MainWindow", "اضافه کردن فایل ها"))
        self.label_7.setText(_translate("MainWindow", "فایل آیدی فایل های پیش نمایش"))
        self.pushButton_5.setText(_translate("MainWindow", "اضافه"))
        self.pushButton_6.setText(_translate("MainWindow", "حذف"))
        self.label_6.setText(_translate("MainWindow", "فایل آیدی فایل های اصلی"))
        self.pushButton_7.setText(_translate("MainWindow", "اضافه"))
        self.pushButton_8.setText(_translate("MainWindow", "حذف"))
        self.pushButton.setText(_translate("MainWindow", "ذخیره"))
        self.pushButton_2.setText(_translate("MainWindow", "ریست"))
        self.pushButton_4.setText(_translate("MainWindow", "ساخت تصادفی"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "کد محصول که به صورت یکتا صادر میگردد."))
        self.label_2.setText(_translate("MainWindow", "کد فایل"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "نام محصول که نام فولدر هم میشود."))
        self.label.setText(_translate("MainWindow", "نام فایل"))
        self.label_8.setText(_translate("MainWindow", "توضیحات:"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "توضیحات محصول در این بخش قرار میگیرند."))
        self.label_5.setText(_translate("MainWindow", "تومان"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "معادل ریالی توکن"))
        self.label_4.setText(_translate("MainWindow", "توکن معادل"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "توکن های مورد نیاز برای خرید فایل"))
        self.label_3.setText(_translate("MainWindow", "قیمت"))
        self.label_9.setText(_translate("MainWindow", "تایید نهایی"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "کد فایل"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "نام فایل"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "توکن"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "قیمت"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "پیش نمایش"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "توضیحات"))
        self.pushButton_9.setText(_translate("MainWindow", "ثبت فایل ها"))
        self.pushButton_10.setText(_translate("MainWindow", "آپلود به سرور"))
        self.pushButton_11.setText(_translate("MainWindow", "بعدی"))
        self.pushButton_3.setText(_translate("MainWindow", "خروج"))
        self.menuFile.setTitle(_translate("MainWindow", "فایل"))
        self.menu.setTitle(_translate("MainWindow", "پیدا کردن فایل آی دی"))
        self.menu_2.setTitle(_translate("MainWindow", "تنظیمات"))
        self.menu_3.setTitle(_translate("MainWindow", "درباره"))
        self.action_2.setText(_translate("MainWindow", "باز کردن فایل اصلی"))
        self.action_3.setText(_translate("MainWindow", "ریست"))
        self.action_4.setText(_translate("MainWindow", "پیش نمایش"))
        self.action_5.setText(_translate("MainWindow", "فایل اصلی"))
        self.action_7.setText(_translate("MainWindow", "خروج"))
        self.action_8.setText(_translate("MainWindow", "پوشه تنظیمات"))
        self.action_9.setText(_translate("MainWindow", "راهنما"))
        self.action_10.setText(_translate("MainWindow", "آپدیت"))
